#!/usr/bin/sh
# Executes all queries inside sync

DBPATH=`ftrponder`
if [ "$DBPATH" = "" ]
then
  echo Not inside a valid database
  exit 1
fi

ftrdrop

function traverse 
{
  for NODE in $1
  do
    if [ -d $NODE ]
    then
      traverse "`echo $NODE/*`"
      continue
    fi
    ftrq $NODE
  done
}

traverse "`echo $DBPATH/sync/*`"