#!/usr/bin/sh
# Addes selected files to tag

DBPATH=`ftrponder`
SOURCEPATH=`cat $DBPATH/config/source`
if [ "$DBPATH" = "" ]
then
  echo Not inside a valid database
  exit 1
fi

FILES=`echo $@ | tr " " "\n" | tail -n +2`
TAG=`echo $@ | tr " " "\n" | head -n 1`
TAGFILE=$DBPATH/tags/$TAG

REALFILES=""

for FILE in $FILES
do
  REALPATH="`ftrreverse $FILE`"
  REALFILES="$REALFILES `realpath --relative-to $SOURCEPATH $REALPATH`" 
done

REALFILES=`echo $REALFILES | tr " " "\n"`

echo "$REALFILES" >> $TAGFILE
NEWTAGCONTENTS=`cat "$DBPATH/tags/$TAG" | sort | uniq`
echo "$NEWTAGCONTENTS" > $TAGFILE